# config file for resourcemanager

# 1=>"debug", 2=>"info", 3=>"warn", 4=>"error", 5=>"fatal"
#log_level: 1

# config for log.
log:
  level: 1 # 1=>"debug", 2=>"info", 3=>"warn", 4=>"error", 5=>"fatal"
  output: "console" # "console" or "file"
  file:
    path: "/tmp/log/resourcemanager/resourcemanager.log"
    max_size: 128 # In MB.
    max_age: 0
    max_backups: 0
    compress: false # determines if the rotated log files should be compressed using gzip.

grpc_server:
  address: "127.0.0.1:9111"  #required
  log_level: 2 #  1 => info, 2 => waring, 3 => error, 4 => fatal
  log_verbosity: 9

metircs_server:
  enable: true
  address: "127.0.0.1:9121"  # required when enabled is true
  url_path: "/metrics"

tracer:
  service_name: "resourcemanager"
  local_agent: "127.0.0.1:6831"

#storeage:
#  background: "hdfs" # Supported value: "hdfs", "s3".
#  hadoop_conf_dir: "config/hadoop"
#  s3:
#    endpoint: "s3.gd2.qingstor.com"
#    region: "gd2" # us-west-2
#    bucket: "demo-yu-gd2-15"
#    access_key_id: "EHUWSTQPAEUFQMSHJRZA"
#    secret_access_key: "Nj8TibC7CKa7aywYkIPVfsgiiDkimLACeK3LUXrQ"
#    disable_ssl: false
#    force_path_style: false

#storage_background: "hdfs" # Supported value: "hdfs", "s3".
#
## HDFS config.
#hadoop_conf_dir: "config/hadoop"
#
#s3_config:
#  endpoint: "s3.gd2.qingstor.com"
#  region: "gd2" # us-west-2
#  bucket: "demo-yu-gd2-15"
#  access_key_id: "EHUWSTQPAEUFQMSHJRZA"
#  secret_access_key: "Nj8TibC7CKa7aywYkIPVfsgiiDkimLACeK3LUXrQ"
#  disable_ssl: false
#  force_path_style: false


#mysql:
#  hosts: "127.0.0.1:3306"  # required
#  users: "root"  # required
#  password: "root"  # required
#  database: "dataomnis"  # required
#  max_idle_conn: 16
#  max_open_conn: 128
#  conn_max_lifetime: 10m
#  log_level: 4 # 1 => Silent, 2 => Error, 3 => Warn, 4 => Info
#  slow_threshold: 2s